// GENERATED BY ./src/scripts/generateComponents.ts
// DO NOT EDIT IT MANUALLY

import React from "react";

import { iconUsdt0Mono } from "../../../icons/mono/build/icon-usdt0_mono.icon";
import { IconComponentBaseProps } from "../../../utils";
import { Image } from "../../Base/Image";

const UsdtZero_monoIcon = (props: IconComponentBaseProps) => {
  return <Image svgCode={iconUsdt0Mono.data} {...props} />;
};

if (process.env.NODE_ENV !== 'production') {
  UsdtZero_monoIcon.displayName = 'UsdtZero_monoIcon';
}

export default UsdtZero_monoIcon;