// GENERATED BY ./src/scripts/generateComponents.ts
// DO NOT EDIT IT MANUALLY

import React from "react";

import { iconUsdt0Full } from "../../../icons/mono/build/icon-usdt0_full.icon";
import { IconComponentBaseProps } from "../../../utils";
import { Image } from "../../Base/Image";

const UsdtZero_fullIcon = (props: IconComponentBaseProps) => {
  return <Image svgCode={iconUsdt0Full.data} {...props} />;
};

if (process.env.NODE_ENV !== 'production') {
  UsdtZero_fullIcon.displayName = 'UsdtZero_fullIcon';
}

export default UsdtZero_fullIcon;