name: release-please
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releaseCreated: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node
          package-name: react-web3-icons
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json

  release-node:
    needs: release-please
    if: ${{ needs.release-please.outputs.releaseCreated }}
    uses: bgd-labs/web3-icons/.github/workflows/release-node.yml@main
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
